= Is nav highlighting broken for navs with multiple entries to the same page?

== What I am trying to do

I have two antora modules (named `mod-A` and `mod-B`) that share content (pages and navs) stored in a third module ( called `shared`). The two modules that use the content appear in the nav menu but the `shared` module doesn't. It is just a holder for shared content that is supposed to be reused.

The `shared` module has navs that are imported by the navs of `mod-A` and `mod-B`. These shared navs contain `xref`s that point to pages within the `shared` module. The problem I have is that when those links are clicked on (either in `mod-A` or `mod-B` 's nav lists), they always change the active item in the menu tree to the first module that imports the shared nav (in this case `mod-A`). Read on for a more detailed description.

== Antora setup

. The configuration in `playbook.yml` is very simple.
There's just one content source (local), and the ui bundle config (default UI).
. All the antora assets/files are under the `book` directory at the root of this repo
. We only have one component called `book`, under the `book` directory.
. The `book` component has 3 modules:
.. `shared`: It contains pages and nav partials that are supposed to be reused in the other two modules described below. The `partials/common-nav.adoc` file has `xref` s pointing to pages in this same `shared` module. This nav partial is imported into the other two modules' navs.
.. `mod-A`: It has a `nav.adoc` at its root, which imports nav lists from the `shared` module's nav partial
.. `mod-B`: It has a `nav.adoc` at its root, which imports nav lists from the `shared` module's nav partial
. The `book` component descriptor file (`antora.yml`) declares only the navs from `mod-A` and `mod-B`, in that order. This means that the `shared` module will not show up in the rendered site's navigation, but the navigation lists of the other modules will be built using the `common-nav.adoc` partial in the `shared` module.

== Actual behaviour (the "bug?")
The nav menus are built okay, but when you open the built site, expand the `Module B` menu item, and click the `Link to common page` item, the menu highlights the `Link to common page` menu item in `Module A` instead of `Module B`.

[NOTE]
====
. This "loss of context" also affects the next/prev navigation links at the bottom of pages. The context for those goes into `Module A` just like the nav menu.
. If I change the order in which the navs are declared in `antora.yml` to import `mod-B/nav.yml` before `mod-A/nav.yml`, the reverse happens. `Module B` 's nav section always gets highlighted.
====

== Expected behaviour

I would like to see `Module B` 's `Link to shared page` menu item highlighted when I click it under `Module B`.

== How to reproduce the problem [[reproduce]]

. Clone this repo and install dependencies
+
[source,bash]
----
# clone this repo
git clone https://github.com/wanderanimrod/antora-broken-nav-with-shared-module.git
cd antora-broken-nav-with-shared-module
----

. Build the site
+
[source,bash]
----
npm install
npx antora generate playbook.yml --stacktrace
----

. Open the site in the browser
+
[[browser]]
[source,bash]
----
open build/site/index.html
----

. Expand the `Module B` item in the nav.
. Click on the `Link to shared page` sub item.
. Notice that the navigation to the page happens, but the menu highlight context (and the breadcrumbs) switch to `Module A`. It should remain in `Module B`.





