= Deeply nested nav files with `include::`

== What I am trying to do

I have two antora modules (named `mod-A` and `mod-B`) that share content (pages and navs) stored in a third module ( called `shared`). The two modules that use the content appear in the nav menu but the `shared` module doesn't. It is just a holder for shared content that is supposed to be reused.

The `shared` module has navs that are imported by the navs of `mod-A` and `mod-B`. These shared navs contain `xref`s that point to pages within the `shared` module. The problem I have is that when those links are clicked on (either in `mod-A` or `mod-B` 's nav lists), they always change the active item in the menu tree to the first module that imports the shared nav (in this case `mod-A`). Read on for a more detailed description.

== Antora setup

. The configuration in `playbook.yml` is very simple.
There's just one content source (local), and the ui bundle config (default UI).
. All the antora assets/files are under the `book` directory at the root of this repo
. We only have one component called `book`, under the `book` directory.
. The `book` component has 3 modules:
.. `shared`: It contains pages and nav partials that are supposed to be reused in the other two modules described below. The `partials/common-nav.adoc` file has `xref` s pointing to pages in this same `shared` module. This nav partial is imported into the other two modules' navs.
.. `mod-A`: It has a `nav.adoc` at its root, which imports nav lists from the `shared` module's nav partial
.. `mod-B`: It has a `nav.adoc` at its root, which imports nav lists from the `shared` module's nav partial
. The `book` component descriptor file (`antora.yml`) declares only the navs from `mod-A` and `mod-B`, in that order. This means that the `shared` module will not show up in the rendered site's navigation, but the navigation lists of the other modules will be built using the `common-nav.adoc` partial in the `shared` module.

== Expected behaviour

The nav menus are built okay, but when you click on
A nav menu that looks like this:

* Chapter 1
** Topic 1
*** Lesson 1
*** Lesson 2
** Topic 2
*** Lesson 1
*** Lesson 2

== Actual behaviour

If you look at the nav menu on the left (xref:#browser[in the browser]), the list items are mangled, and some are missing!
For quick reference, here's the broken nav menu I get:

* Chapter 1
** Topic 1
* Lesson 1
* Lesson 2
* Lesson 1
* Lesson 2

Interestingly, IntelliJ's Asciidoctor extension is also broken, but not in teh same way.
It preserves all the list items, but the nesting is still broken.
This is what it renders:

* Chapter 1
** Topic 1
* Lesson 1
* Lesson 2
* Topic 2
* Lesson 1
* Lesson 2


== How to reproduce the problem [[reproduce]]

. Clone this repo and install dependencies
+
[source,bash]
----
# clone this repo
git clone https://github.com/wanderanimrod/antora-deep-nav-nesting.git
cd antora-deep-nav-nesting
----

. Build the site
+
[source,bash]
----
npm install
npx antora generate playbook.yml --stacktrace
----

. Open the site in the browser
+
[[browser]]
[source,bash]
----
open build/site/index.html
----





